In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns   
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder, MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv(r'D:\Healthcare\healthcare\data\cleaned\clean.csv')
df

       Age  Gender Blood Type  ... Admission Type   Medication  Test Results
0       30    Male         B-  ...         Urgent  Paracetamol        Normal
1       62    Male         A+  ...      Emergency    Ibuprofen  Inconclusive
2       76  Female         A-  ...      Emergency      Aspirin        Normal
3       28  Female         O+  ...       Elective    Ibuprofen      Abnormal
4       43  Female        AB+  ...         Urgent   Penicillin      Abnormal
...    ...     ...        ...  ...            ...          ...           ...
55495   42  Female         O+  ...       Elective   Penicillin      Abnormal
55496   61  Female        AB-  ...       Elective      Aspirin        Normal
55497   38  Female         B+  ...         Urgent    Ibuprofen      Abnormal
55498   43    Male         O-  ...       Elective    Ibuprofen      Abnormal
55499   53  Female         O+  ...         Urgent    Ibuprofen      Abnormal

[55500 rows x 9 columns]

In [4]:
X=df.drop('Billing Amount',axis=1)
y=df['Billing Amount']

In [5]:
X

       Age  Gender Blood Type  ... Admission Type   Medication  Test Results
0       30    Male         B-  ...         Urgent  Paracetamol        Normal
1       62    Male         A+  ...      Emergency    Ibuprofen  Inconclusive
2       76  Female         A-  ...      Emergency      Aspirin        Normal
3       28  Female         O+  ...       Elective    Ibuprofen      Abnormal
4       43  Female        AB+  ...         Urgent   Penicillin      Abnormal
...    ...     ...        ...  ...            ...          ...           ...
55495   42  Female         O+  ...       Elective   Penicillin      Abnormal
55496   61  Female        AB-  ...       Elective      Aspirin        Normal
55497   38  Female         B+  ...         Urgent    Ibuprofen      Abnormal
55498   43    Male         O-  ...       Elective    Ibuprofen      Abnormal
55499   53  Female         O+  ...         Urgent    Ibuprofen      Abnormal

[55500 rows x 8 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
df1=pd.read_csv(r'D:\Healthcare\healthcare\data\cleaned\processed.csv')
df1